import os
from dotenv import load_dotenv
import flet as ft

# Load environment variables from .env file
# Note: .env files are not bundled in Android APK builds
# For production builds, you should either:
#   1. Use the build script to inject values (recommended)
#   2. Hardcode production values in the Config class below

# Resolve .env path relative to the project root (parent of src/)
_config_dir = os.path.dirname(os.path.abspath(__file__))  # src/core/
_project_root = os.path.dirname(os.path.dirname(_config_dir))  # Lakb.ai/
_env_path = os.path.join(_project_root, '.env')

if os.path.exists(_env_path):
    load_dotenv(_env_path)
    print(f"INFO: Loading environment variables from {_env_path} (development mode)")
elif os.path.exists('.env'):
    load_dotenv()
    print("INFO: Loading environment variables from .env file (development mode)")
else:
    print("INFO: No .env file found - using environment variables or defaults (production mode)")

# Try to import build_secrets (auto-generated by build_apk.py for APK builds)
# This provides fallback values when .env is not available (i.e., inside the APK)
try:
    from core import build_secrets as _secrets
    print("INFO: build_secrets module found (APK build mode)")
except ImportError:
    _secrets = None


def _get(var_name: str, default: str = "") -> str:
    """Get a config value from env vars first, then fall back to build_secrets.
    
    Priority: environment variable > build_secrets > default
    """
    val = os.getenv(var_name)
    if val:
        return val
    if _secrets and hasattr(_secrets, var_name):
        val = getattr(_secrets, var_name)
        if val:
            return val
    return default

# Centralized app window configuration
APP_WIDTH: int = 412
APP_HEIGHT: int = 917
APP_TITLE: str = "Lakb.ai"
APP_RESIZABLE: bool = False
APP_PADDING: int | float = 0


def configure_page(page: ft.Page, *, title: str | None = None) -> None:
    """
    Apply common window configuration to the given Flet page.

    Args:
        page: The Flet `Page` instance to configure.
        title: Optional custom window title; falls back to `APP_TITLE`.
    """

    # Basic properties
    page.title = title or APP_TITLE
    page.padding = APP_PADDING

    # Handle both older top-level window_* properties and the newer
    # `page.window` object, so the config works across runtimes.
    # Desktop/web runtimes
    if getattr(page, "window", None) is not None:
        page.window.width = APP_WIDTH
        page.window.height = APP_HEIGHT
        page.window.resizable = APP_RESIZABLE
        page.window.maximizable = APP_RESIZABLE

    # Backwards/alternative attributes (no-op if not present)
    if hasattr(page, "window_width"):
        page.window.width = APP_WIDTH
    if hasattr(page, "window_height"):
        page.window.height = APP_HEIGHT
    if hasattr(page, "window_resizable"):
        page.window.resizable = APP_RESIZABLE


class Config:
    """Application configuration.
    
    For Android APK builds:
    - .env files are NOT included in the APK
    - build_secrets.py is auto-generated by build_apk.py and bundled into the APK
    - The _get() helper checks: env var → build_secrets → default value
    """
    
    # API Keys
    # Development: Loaded from .env via environment variables
    # Production (APK): Loaded from build_secrets.py (auto-generated by build_apk.py)
    
    GOOGLE_PLACES_API_KEY = _get("GOOGLE_PLACES_API_KEY")
    MAPS_STATIC_API_KEY = _get("MAPS_STATIC_API_KEY")
    OPENWEATHER_API_KEY = _get("OPENWEATHER_API_KEY")
    GEMINI_API_KEY = _get("GEMINI_API_KEY")
    CALENDARIFIC_API_KEY = _get("CALENDARIFIC_API_KEY")
    OPENAQ_API_KEY = _get("OPENAQ_API_KEY")

    # Base URLs
    GOOGLE_PLACES_BASE_URL = "https://maps.googleapis.com/maps/api/place"
    OPENWEATHER_BASE_URL = _get("OPENWEATHER_BASE_URL", "https://api.openweathermap.org/data/2.5")
    GEMINI_BASE_URL = _get("GEMINI_BASE_URL", "https://generativelanguage.googleapis.com/v1beta")
    CALENDARIFIC_BASE_URL = _get("CALENDARIFIC_BASE_URL", "https://calendarific.com/api/v2")
    OPENAQ_BASE_URL = _get("OPENAQ_BASE_URL", "https://api.openaq.org/v3")

    # Supabase - CRITICAL: These MUST be set for the app to work!
    SUPABASE_URL = _get("SUPABASE_URL")
    SUPABASE_KEY = _get("SUPABASE_KEY")
    
    # Google OAuth
    GOOGLE_CLIENT_ID = _get("GOOGLE_CLIENT_ID")
    GOOGLE_CLIENT_SECRET = _get("GOOGLE_CLIENT_SECRET")
    
    # OAuth Redirect URL (for Google Sign-In callback)
    # Platform-specific configuration:
    # - Android: Uses custom URL scheme for deep linking (lakbai://oauth_callback)
    # - Desktop/Web: Uses localhost for development (http://localhost:8550/api/oauth/redirect)
    
    # Android deep link redirect URL
    ANDROID_REDIRECT_URL = _get("ANDROID_REDIRECT_URL", "lakbai://oauth_callback")
    
    # Desktop/Web redirect URL (for development)
    DESKTOP_REDIRECT_URL = _get("REDIRECT_URL", "http://localhost:8550/api/oauth/redirect")
    
    # Legacy support
    REDIRECT_URL = _get("REDIRECT_URL")
    
    @classmethod
    def is_android(cls, page: ft.Page = None) -> bool:
        """Detect if the app is running on Android platform."""
        # Use reliable Flet page platform if available
        if page is not None:
             if hasattr(page, 'platform'):
                 return page.platform == ft.PagePlatform.ANDROID
                 
        try:
            import platform
            system = platform.system().lower()
            
            # Check if running on Android
            # Flet on Android typically reports 'linux' but we can check environment
            if system == 'linux':
                # Check for Android-specific environment indicators
                if os.path.exists('/system/build.prop'):
                    return True
                # Check environment variables that might indicate Android
                if 'ANDROID_ROOT' in os.environ or 'ANDROID_DATA' in os.environ:
                    return True
            
            return False
        except Exception as e:
            print(f"Error detecting platform: {e}")
            return False
    
    @classmethod
    def get_redirect_url(cls, page: ft.Page = None, is_android: bool = None) -> str:
        """
        Get the appropriate redirect URL based on the platform.
        
        On Android, ALWAYS returns the deep-link URL (lakbai://oauth_callback)
        so the OS routes the OAuth callback back into the app.
        On Desktop/Web, returns the localhost redirect URL for development.
        
        Args:
            page: Flet page instance for reliable platform detection
            is_android: Optional explicit platform override. If None, auto-detects.
        
        Returns:
            Platform-appropriate redirect URL
        """
        # Allow explicit override for testing
        if is_android is None:
            is_android = cls.is_android(page)
        
        # Platform detection takes priority — Android MUST use the deep link
        # so the OS can route the callback back to the app instead of localhost
        if is_android:
            print(f"INFO: Using Android redirect URL: {cls.ANDROID_REDIRECT_URL}")
            return cls.ANDROID_REDIRECT_URL
        
        # Desktop/Web: use explicit env var if set, otherwise fall back to default
        if cls.REDIRECT_URL:
            print(f"INFO: Using configured redirect URL: {cls.REDIRECT_URL}")
            return cls.REDIRECT_URL
        
        print(f"INFO: Using Desktop/Web redirect URL: {cls.DESKTOP_REDIRECT_URL}")
        return cls.DESKTOP_REDIRECT_URL

    @classmethod
    def validate(cls):
        """Validate that essential configuration is present."""
        missing = []
        if not cls.GOOGLE_PLACES_API_KEY:
            missing.append("GOOGLE_PLACES_API_KEY")
        
        # Warn about optional but recommended services
        warnings = []
        if not cls.SUPABASE_URL or not cls.SUPABASE_KEY:
            warnings.append("Supabase credentials not configured - authentication and data persistence will not work")
        
        if missing:
            print(f"Warning: Missing configuration keys: {', '.join(missing)}")
        
        if warnings:
            for warning in warnings:
                print(f"Warning: {warning}")